name: webbpulse_inventory_management
description: "A program built in flutter to do simple tracking of device checkout status."
publish_to: 'none'
version: 1.1.0
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  go_router: ^14.2.0
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  provider: ^6.1.1
  firebase_ui_auth: ^1.13.0
  rxdart: ^0.28.0
  intl: ^0.19.0
  csv: ^6.0.0
  file_picker: ^8.0.7
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  universal_html: ^2.2.4
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.2
  firebase_ui_oauth_google: ^1.3.2
  firebase_ui_oauth_apple: ^1.2.20
  cloud_functions: ^5.1.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/boxes.jpg
