// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwixRxUPRS-4wf6HHn86jEVlJXY19ff-Q',
    appId: '1:1006892799648:web:fbc7a4eee88d8b24505bc5',
    messagingSenderId: '1006892799648',
    projectId: 'webbpulse-checkout',
    authDomain: 'webbpulse-checkout.firebaseapp.com',
    storageBucket: 'webbpulse-checkout.appspot.com',
    measurementId: 'G-FE06S4S2WX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa1MyglYmLW-1aH56gf0ebUGT9CiWOqk0',
    appId: '1:1006892799648:android:c20fd277d6568ec1505bc5',
    messagingSenderId: '1006892799648',
    projectId: 'webbpulse-checkout',
    storageBucket: 'webbpulse-checkout.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTRRCFfStJAs1uXf9vofVcn7lYphrvOdo',
    appId: '1:1006892799648:ios:1618865b1a1e4ba3505bc5',
    messagingSenderId: '1006892799648',
    projectId: 'webbpulse-checkout',
    storageBucket: 'webbpulse-checkout.appspot.com',
    androidClientId: '1006892799648-c7tvdgurqn8j562sl05b87t0nicgg9db.apps.googleusercontent.com',
    iosClientId: '1006892799648-0h2f27fk2eod4qkav0ri61184h56fldi.apps.googleusercontent.com',
    iosBundleId: 'com.example.webbpulseCheckout',
  );
}
