// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArykTTCGzvOaRDOmd2LWLjSYSkSfDyvCU',
    appId: '1:511369160204:web:939440552e8a52eca73029',
    messagingSenderId: '511369160204',
    projectId: 'webbcheck',
    authDomain: 'webbcheck.firebaseapp.com',
    storageBucket: 'webbcheck.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV8sHYVYw2LIVqyov8d9HGCL7Qw_7FtT8',
    appId: '1:511369160204:android:b5650e3c5edf9892a73029',
    messagingSenderId: '511369160204',
    projectId: 'webbcheck',
    storageBucket: 'webbcheck.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZooaskVDJslRmi0cvqzRWfEWqzuPSZsI',
    appId: '1:511369160204:ios:0e16363d1ef050e8a73029',
    messagingSenderId: '511369160204',
    projectId: 'webbcheck',
    storageBucket: 'webbcheck.appspot.com',
    iosBundleId: 'com.example.webbpulseCheckout',
  );
}
