name: Deploy on merge to appstore testing

on:
  push:
    branches:
      - appstore-deploy-testing

jobs:
    build_and_deploy_testflight_ios_app:
        name: Build and Deploy Testflight IOS App
        runs-on: macos-latest
        env:
            FLUTTER_VERSION: 3.24.3
            FIREBASE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_APPLICATION_CREDENTIALS }}
            GOOGLE_APPLICATION_CREDENTIALS: gcp_key.json
        
        steps:
            -   name: Checkout Repo
                uses: actions/checkout@main
                
            -   name: Upload to App Store
                env:
                    APPLE_ID: ${{ secrets.APPLE_ID }}
                    APPLE_APP_PASSWORD: ${{ secrets.APPLE_APP_PASSWORD }}
                run: |
                    cd flutter
                    xcrun altool --upload-app -f ipa/webbpulse_inventory_management.ipa -t ios -u "$APPLE_ID" -p "$APPLE_APP_PASSWORD"